# Generated by Django 3.2.4 on 2021-07-02 15:12

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', froala_editor.fields.FroalaField()),
                ('slug', models.SlugField(max_length=500)),
                ('image', models.ImageField(upload_to=None, verbose_name='/nitin')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('upload_to', models.DateTimeField(auto_now=True, verbose_name='')),
            ],
        ),
    ]
