# Generated by Django 3.2.4 on 2021-07-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload_to',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
