# Generated by Django 3.2.4 on 2021-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idi', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('le', models.IntegerField()),
            ],
        ),
    ]
